# -*- coding: utf-8 -*-
"""pandas practice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zU63MxgQ1ZPo54Ux09KgBSC9sFcPzmqY
"""

import pandas as pd
import numpy as np
#create series
s = pd.Series([10,20,30,40],index = ['a','b','c','d'])
print(s)
#create dataframe
d = {
    'Name' : ['abc','def','lmn','xyz'],
    'Age' : [24,25,23,22],
    'Salary' : [10000,20000,300000,400000]
}
df = pd.DataFrame(d)
print("dataframe :",df)
print("row with label 1 use loc:",df.loc[1])
print("first two rows using iloc:",df.iloc[0:2])

print("select name column ",df['Name'])
print("select name and age column ",df[['Name','Age']])
print(df[df['Salary']>100000])

# Add a new column based on calculations
df['Bonus'] = df['Salary'] * 0.1
print("\nDataFrame with Bonus column:")
print(df)

# Rename columns using rename()
print("\nRename columns:")
df_renamed = df.rename(columns={'Salary': 'BaseSalary'})
print(df_renamed)

# Sort rows by a column in descending order
print("\nSort by Age descending:")
print(df.sort_values(by='Age', ascending=False))

# Group by a derived boolean column and calculate mean
print("\nGroup by operation (average salary by age > 30 or not):")
df['AgeGroup'] = df['Age'] >=24
print(df.groupby('AgeGroup')['Salary'].mean())


# Sort rows by a column in descending order
print("\nSort by Age descending:")
print(df.sort_values(by='Age', ascending=False))
print(df.dtypes)
print(df.head(3))
print(df.tail(3))
# Compute central tendency measures
print("\nMean Age:", df['Age'].mean())
print("Median Salary:", df['Salary'].median())

# Compute spread measures
print("Standard Deviation of Salary:", df['Salary'].std())
print("Variance of Salary:", df['Salary'].var())


# Correlation and Covariance between columns
print("\nCorrelation between Age and Salary:")
print(df[['Age', 'Salary']].corr())

print("\nCovariance between Age and Salary:")
print(df[['Age', 'Salary']].cov())

# Frequency of values
print("\nValue counts for AgeGroup:")
print(df['AgeGroup'].value_counts())

#load data from excel file
df = pd.read_excel('/content/HR Data.xlsx')
print(df)
df.head()
df.tail()
df.describe()
df.info()

